Add Matus Goljer as author
DamienCassou/beginend pull request #36
Opened 2017-06-02 19:37 UTC by DamienCassou

2017-06-05 08:55 UTC, Fuco1 requested changes

2017-06-05 08:55 UTC, Fuco1 commented on beginend.el
> +;; Authors: Damien Cassou <damien@cassou.me> and Matus Goljer <matus.goljer@gmail.com>
If there are multiple authors they should be listed on separate lines, see `Author` https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html

2017-06-05 08:56 UTC, Fuco1 commented on beginend.el
> +;; Authors: Damien Cassou <damien@cassou.me> and Matus Goljer <matus.goljer@gmail.com>
This is "necessary" so that the package tools can properly read the metadata.

2017-06-05 09:05 UTC, DamienCassou commented on beginend.el
> +;; Authors: Damien Cassou <damien@cassou.me> and Matus Goljer <matus.goljer@gmail.com>
Fixed. Thanks

2017-06-18 10:13 UTC, DamienCassou commented
Up

2017-06-18 10:27 UTC, Fuco1 approved these changes

2017-06-18 11:56 UTC, merged